sudo: required

matrix:
  allow_failures:
  - language: node_js

  include:
  - language: rust
    rust: nightly
    cache: cargo

    install:
      - mdbook -V || cargo install mdbook --vers "^0.2.0"
    script: >
      mdbook build
      && mdbook test
      && docker run --rm -t -v "$(pwd):/app/md/" mihazupan/markdownvalidator:latest --threshold 10

    deploy:
      provider: pages
      local-dir: book
      skip-cleanup: true
      github-token: $GITHUB_TOKEN
      keep-history: true
      on:
        branch: master

    notifications:
      email:
        on_success: never
        on_failure: always


  - language: node_js
    node_js: node

    install:
      - npm install -g cspell

    script:
      - cspell "src/**/*.md"

## Notes:
### Limit concurrent jobs to only 1
### Disable building PRs (might expose environment variables)
